# Generated by Django 4.1.3 on 2022-12-14 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikiWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 15, 55, 898503)),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 17, 15, 55, 898503)),
        ),
    ]
