# Generated by Django 4.1.3 on 2022-12-14 07:59

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("wikiWebsite", "0002_alter_article_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 14, 7, 59, 23, 873965)
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="date_last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 14, 7, 59, 23, 873994)
            ),
        ),
    ]
