# Generated by Django 4.1.3 on 2022-12-14 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "wikiWebsite",
            "0003_alter_article_content_alter_article_date_created_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 14, 8, 9, 36, 289571)
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="date_last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 14, 8, 9, 36, 289598)
            ),
        ),
    ]
